-- AlterTable
ALTER TABLE "OrdenCompra" ADD COLUMN     "fechaContable" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "PreFactura" ADD COLUMN     "fechaContable" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
