-- CreateEnum
CREATE TYPE "TipoTasa" AS ENUM ('EFECTIVA_ANUAL', 'NOMINAL_ANUAL', 'EFECTIVA_MENSUAL', 'NOMINAL_MENSUAL', 'EFECTIVA_DIARIA');

-- CreateEnum
CREATE TYPE "PeriodicidadRendimiento" AS ENUM ('VENCIMIENTO', 'DIARIA', 'SEMANAL', 'QUINCENAL', 'MENSUAL', 'BIMESTRAL', 'TRIMESTRAL', 'CUATRIMESTRAL', 'SEMESTRAL', 'ANUAL');

-- CreateEnum
CREATE TYPE "TipoDesembolso" AS ENUM ('TOTAL', 'PARCIAL', 'PROGRAMADO');

-- CreateEnum
CREATE TYPE "TipoGarantiaReal" AS ENUM ('INMUEBLE', 'VEHICULO', 'MAQUINARIA', 'INVENTARIO', 'CUENTAS_COBRAR', 'DEPOSITO_PLAZO', 'VALORES', 'OTROS');

-- CreateEnum
CREATE TYPE "EstadoGarantia" AS ENUM ('VIGENTE', 'LIBERADA', 'EJECUTADA', 'VENCIDA', 'RENOVADA');

-- CreateEnum
CREATE TYPE "TipoCobro" AS ENUM ('CUOTA_NORMAL', 'PREPAGO_PARCIAL', 'PREPAGO_TOTAL', 'MORA', 'COMISION', 'SEGURO');

-- CreateEnum
CREATE TYPE "MetodoPago" AS ENUM ('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'DEBITO_AUTOMATICO', 'TARJETA_CREDITO', 'TARJETA_DEBITO');

-- CreateEnum
CREATE TYPE "EstadoDesembolso" AS ENUM ('PENDIENTE', 'PROCESADO', 'CONFIRMADO', 'RECHAZADO', 'ANULADO');

-- CreateEnum
CREATE TYPE "TipoRenovacion" AS ENUM ('AUTOMATICA', 'MANUAL', 'SIN_RENOVACION');
